version: '3'
services:
  backstage:
    image: backstage:build
    environment:
      # This value must match the name of the postgres configuration block.
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
    ports:
      - '7007:7007'
    command: ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust